services:                                                                                                                                                                                                 
  gomoku:
    image: denoland/deno
    container_name: gomoku
    ports:
      - 0.0.0.0:80:3001
    working_dir: /app
    volumes:
      - ./:/app
    command: deno task dev
    restart: always
